//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Author { get; set; }
        public string Url { get; set; }
        public string Picture { get; set; }
        public string Publisher { get; set; }
        public string ISBN { get; set; }
        public string Language { get; set; }
        public string Binding { get; set; }
        public string Page_extent { get; set; }
        public string Barcode { get; set; }
        public string Series { get; set; }
        public Nullable<int> OzonBookId { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
